### ISSUE TITLE
Changing Keyboard Layout with Alt-Shift problem

### ISSUE THREAD

**Issue by ZeroBit** [Enrico204/Whatsapp-Desktop#34]
In Archlinux KDE when I try to switch keyboard layout with Alt-Shift, the sub-menu File -> Quit Ctrl-Q appears in the left upper corner, instead of changing layout to another language. Alt-Shift is the standard combination for many users to change keyboard layout. Please, fix it. Thank you.

**Comment by Enrico204** [comment]
There is no such shortcut in WhatsApp-desktop code. I'll setup a dev VM with Archlinux and KDE as soon as possible to check why the app is having this behaviour :-)

**Comment by ZeroBit** [comment]
I've small video (with blurred contacts area to show a problem. You can download or watch it on poor quality [here](https://my.pcloud.com/publink/show?code=XZwQpk7Z9ct6dQeHNuf9HWX1DEpeM8OE1u9X)

**Comment by Enrico204** [comment]
Thank you for these links - This week I'll be very busy, but I'll try to check this bug and see where this behaviour is coming from :-)

**Comment by ZeroBit** [comment]
Thank you very much for working on the project!!!

**Comment by Enrico204** [comment]
Hi @ZeroBit , I tried by I can't reproduce your issue. I loaded a VM with Manjaro and added English and Russian languages. Then I tried to press Alt-Shift but nothing happened. Maybe it's not the default. How can I add the Alt-Shift shortcut for keyboard swapping?
PS: sorry I don't use KDE as my desktop environment

**Comment by ZeroBit** [comment]
Go to System Settings -> Input devices -> Keyboard -> Layouts 
Checkbox "Configure layouts" Add Russian (Russian)
Button Shortcuts for Switching Layout "Main shortcuts"

![screenshot_20171006_225354](https://user-images.githubusercontent.com/6258813/31295977-55661390-aae9-11e7-84e6-e71d42dc1907.png)
![screenshot_20171006_225253](https://user-images.githubusercontent.com/6258813/31295978-5566fb66-aae9-11e7-9bc7-6a4cfb6ece24.png)
 
Thank you

in Manjaro you can use 
$ yaourt -S whatsapp-desktop
to install your app

But before (probably) you should add yaourt as described [here](https://www.ostechnix.com/install-yaourt-arch-linux/)

Just 4 steps 
1. sudo nano /etc/pacman.conf
2. add in the end the lines:
[archlinuxfr]
SigLevel = Never
Server = http://repo.archlinux.fr/$arch
3. sudo pacman -Syy
4. sudo pacman -S yaourt

**Comment by Enrico204** [comment]
I traced back the issue and I found this tricky method: adding "&" before menu labels disable alt-shift behavior. So this issue is resolved ;-)
Thanks for help! :-)

**Comment by ZeroBit** [comment]
Thank you very, vary much for fixing this bug! Will you be able to create WhatsApp-linux-x64.tar.gz [here](https://github.com/Enrico204/Whatsapp-Desktop/releases) ?

**Comment by Enrico204** [comment]
Yes, I'll create a new release after all tasks for [current milestone](https://github.com/Enrico204/Whatsapp-Desktop/milestone/3) are completed :-)

**Comment by ZeroBit** [comment]
The problem with switching layouts has gone!
But the icon is still the same

`[user@book ~]$ Whatsapp 
[16:54:13:0397] [info] Log init, file /home/user/.config/whatsapp-desktop/log.log
[16:54:13:0407] [info] Loading locale en_US
[16:54:13:0413] [info] Loading locale it_IT
[16:54:13:0417] [info] Setting locale en_US
[16:54:13:0420] [info] Loading configuration
[16:54:13:0421] [info] Configuration loaded from /home/user/.config/whatsapp-desktop/settings.json
[16:54:13:0459] [info] Creating menu
[16:54:13:0465] [info] Clearing cache
[16:54:13:0465] [warn] Error clearing cache: Error: ENOENT: no such file or directory, unlink '/home/user/.config/whatsapp-desktop/Application Cache/Index'
[16:54:13:0470] [info] Open main window
[16:54:13:0544] [info] Applying configuration
[16:54:13:0545] [info] Creating tray icon
[16:54:14:0158] [info] Badge updated: 
[16:54:15:0163] [info] Badge updated: 
[16:54:15:0847] [info] Checking for new versions (current version 0.3.13)
[16:54:16:0507] [info] Already on latest version
[16:54:17:0021] [info] Setting tray icon to warning
[16:54:17:0022] [info] Setting tray icon to normal
[16:54:17:0026] [info] Mask value: 1
[16:54:19:0034] [info] Setting tray icon to normal
[16:54:19:0036] [info] Mask value: 0
`
![screenshot_20171007_165658](https://user-images.githubusercontent.com/6258813/31308509-8fe96494-ab80-11e7-86b4-d644e85220ab.png)

**Comment by ZeroBit** [comment]
@Enrico204 
Thank you very much! You're an excellent developer. This bug is resolved totally and quickly!
